export enum UserRoleEnum {
	SUPER_ADMIN = 'SUPER_ADMIN',
	ADMIN = 'ADMIN',
	SEMI_ADMIN = 'SEMI_ADMIN',
	USER = 'USER'
}

export enum UserPermissionEnum {
	ADMIN_READ = 'ADMIN_READ',
	ADMIN_WRITE = 'ADMIN_WRITE',
	REVIEW_READ = 'REVIEW_READ',
	REVIEW_WRITE = 'REVIEW_WRITE',
	CANCELLATION_READ = 'CANCELLATION_READ',
	CANCELLATION_WRITE = 'CANCELLATION_WRITE'
}
